version: "3.8"

services:
  app:
    build: ./api
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=mongodb://db:27017
      - REDIS_URL=redis://cache:6379
    depends_on:
      - db
      - cache
    networks:
      - backend_network

  db:
    image: mongo:latest
    volumes:
      - mongo_data:/data/db
    networks:
      - backend_network

  cache:
    image: redis:latest
    volumes:
      - redis_data:/data
    networks:
      - backend_network

volumes:
  mongo_data:
  redis_data:

networks:
  backend_network:
