version: "3.8"

services:
  db:
    image: mongo
    volumes:
      - mongo_data:/data/db
    ports:
      - 27017:27017

  api:
    build: ./app
    ports:
      - 3000:3000
    depends_on:
      - db
    healthcheck:
      test: curl --fail http://localhost:3000/health || exit 1
      interval: 30s
      timeout: 30s
      start_period: 20s
      retries: 3

volumes:
  mongo_data:
