version: "3.8"

services:
  app:
    image: app
    build:
      dockerfile: ./Dockerfile
      args:
        GIT_REPO: https://github.com/szymon-kalkowski/meme-generator.git
    ports:
      - 80:80
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
