version: "3.4"

services:
  lab03-app:
    image: app
    container_name: app
    build:
      context: ./app
      dockerfile: ./Dockerfile
    volumes:
      - ./app:/usr/src/app
    ports:
      - "3000:3000"

  lab03-nginx:
    build:
      context: ./nginx
      dockerfile: ./Dockerfile
    ports:
      - "80:80"
      - "443:443"
