version: "3.4"

services:
  app:
    image: app
    container_name: app
    build:
      context: ./app
      dockerfile: ./Dockerfile
    volumes:
      - ./app:/usr/src/app
    ports:
      - "3000:3000"

  nginx:
    image: nginx
    container_name: nginx
    build:
      context: ./ngnix
      dockerfile: ./Dockerfile
    ports:
      - "80:80"
      - "443:443"
